# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x03rnr\"=\n\x03Job\x12\x0f\n\x07version\x18\x01 \x01(\x03\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x17\n\x04root\x18\x03 \x01(\x0b\x32\t.rnr.Task\"a\n\x04Task\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x05state\x18\x03 \x01(\x0e\x32\x0e.rnr.TaskState\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x1b\n\x08\x63hildren\x18\x05 \x03(\x0b\x32\t.rnr.Task\":\n\x0bTaskRequest\x12\x0c\n\x04path\x18\x01 \x03(\t\x12\x1d\n\x05state\x18\x02 \x01(\x0e\x32\x0e.rnr.TaskState*X\n\tTaskState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\x0b\n\x07SUCCESS\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x12\x0b\n\x07SKIPPED\x10\x05\x42\x06Z\x04./pbb\x06proto3')

_TASKSTATE = DESCRIPTOR.enum_types_by_name['TaskState']
TaskState = enum_type_wrapper.EnumTypeWrapper(_TASKSTATE)
UNKNOWN = 0
PENDING = 1
RUNNING = 2
SUCCESS = 3
FAILED = 4
SKIPPED = 5


_JOB = DESCRIPTOR.message_types_by_name['Job']
_TASK = DESCRIPTOR.message_types_by_name['Task']
_TASKREQUEST = DESCRIPTOR.message_types_by_name['TaskRequest']
Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), {
  'DESCRIPTOR' : _JOB,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:rnr.Job)
  })
_sym_db.RegisterMessage(Job)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:rnr.Task)
  })
_sym_db.RegisterMessage(Task)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKREQUEST,
  '__module__' : 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:rnr.TaskRequest)
  })
_sym_db.RegisterMessage(TaskRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _TASKSTATE._serialized_start=242
  _TASKSTATE._serialized_end=330
  _JOB._serialized_start=20
  _JOB._serialized_end=81
  _TASK._serialized_start=83
  _TASK._serialized_end=180
  _TASKREQUEST._serialized_start=182
  _TASKREQUEST._serialized_end=240
# @@protoc_insertion_point(module_scope)
